version: 1
services:
  - type: web
    name: my-flask-portfolio
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:10000 app.main:app  # Adjust this based on your project structure
